name: Sync Repository

on:
  schedule:
    # 每6小时运行一次
    - cron: '0 */6 * * *'
  # 允许手动触发
  workflow_dispatch:

# 添加权限配置
permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout target repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"

      - name: Download source repository
        run: |
          # 下载源仓库的zip文件
          curl -L https://github.com/ls125781003/tvboxtg/archive/refs/heads/main.zip -o source.zip
          # 解压文件
          unzip source.zip
          # 删除不需要的文件
          rm source.zip
          # 移动所有文件到当前目录
          mv tvboxtg-main/* .
          mv tvboxtg-main/.* . 2>/dev/null || true
          # 删除解压后的目录
          rm -rf tvboxtg-main
          # 删除 .git 目录（如果存在）
          rm -rf .git

      - name: Commit and push changes
        run: |
          # 添加所有文件
          git add .
          # 检查是否有更改
          if [[ -n "$(git status --porcelain)" ]]; then
            echo "Changes detected, committing and pushing..."
            git commit -m "Sync: Update from source repository [skip ci]"
            git push origin main
            echo "Changes pushed successfully"
          else
            echo "No changes to sync"
          fi 